[package]
name = "hubt"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[dependencies]
#sha2 = { version = "0.10", features = ["asm"] }
sha2 = { version = "0.10" }
rayon = "1.8"
rocksdb = "0.21"
