[package]
name = "vecpak"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_bytes = "0.11"

[lib]
name = "vecpak"
path = "src/lib.rs"
crate-type = ["rlib"]
